# SPDX-License-Identifier: Apache-2.0
[Unit]
RequiresMountsFor=/etc/tls/session-ticket-keys

[Service]
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=/etc/tls/session-ticket-keys
ProtectHome=yes
PrivateDevices=yes
PrivateTmp=yes
CapabilityBoundingSet=
RestrictAddressFamilies=AF_UNIX
RestrictNamespaces=yes
MemoryDenyWriteExecute=yes
LimitCORE=0
